### ISSUE TITLE
JSON exporter produce invalid json for empty entity

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/FameJava#18]
from: [VerveineJ/issues/120](https://github.com/moosetechnology/VerveineJ/issues/120)

When an entity as no attribute, the exporter puts an extra comma which breaks json format

**Comment by badetitou** [comment]
I can reproduce this issue.

**Comment by badetitou** [comment]
fixed in https://github.com/moosetechnology/VerveineJ/issues/120
